#!/bin/bash
#
# +--------------------------------------------------------------------------------+
# | Copyright (C) 2016 Fedora United                                               |
# |                                                                                |
# |This program is free software; You can distribute it and / or                   |
# |modify it under the terms of the GNU General Public License                     |
# |as published by the Free Software Foundation; any                               |
# |version 3 of the License, or (optionally) any version                           |
# |later. http://www.gnu.org/licenses/gpl-3.0.html                                 |
# |This program is distributed in the hope that it will be useful,                 |
# |but WITHOUT ANY WARRANTY. See the GNU General Public License                    |
# |for details.                                                                    |
# +--------------------------------------------------------------------------------+
# |This code is designed, written and maintained by Fedora United team  	   |
# |Any questions, comments or advice on this code                                  |
# |should be addressed to:                                                         |
# |https://github.com/FedoraUnited                                                 |
# +--------------------------------------------------------------------------------+

# REMEMBER MAKE A SSH KEY AND INTEGRATE TO GITHUB

rm -f /tmp/packages.txt

wait ${!}

# The script will make a new tree for ALL packages
 ls $HOME/enjoy24/srpm/ | grep .src.rpm | awk -F'-[0-9]' '{print $1}' | tee /tmp/packages.txt

# The script will make a new tree for new packages (15 days)
# find $HOME/enjoy24/srpm/ -mtime -15 -print | grep .src.rpm | awk -F'srpm/' '{print $2}' | awk -F'-[0-9]' '{print $1}' | egrep -v "^$" | tee /tmp/packages.txt

file=/tmp/packages.txt
mkdir -p $HOME/FedoraUnited


# Tree

while IFS= read -r line; do
repo_name=$line
if [ ! -f $HOME/FedoraUnited/$repo_name/.git/description ]; then
        # display $line or do something with $line
	mkdir -p $HOME/FedoraUnited/$line/SOURCES/ 
	mkdir -p $HOME/FedoraUnited/$line/SRPM/ 
	mkdir -p /tmp/$line/
cp -f $HOME/enjoy24/srpm/$line-[0-9]*.src.rpm /tmp/
rpm_source=$(ls /tmp/$line-[0-9]*.src.rpm | sort | tail -n 1) 
pushd /tmp/$line/
rpm2cpio $rpm_source | cpio -idmv
files=$(ls /tmp/$line/ | grep -vie .spec -e SOURCES)
mv -f $files $HOME/FedoraUnited/$line/SOURCES/
mv -f *.spec $HOME/FedoraUnited/$line/
cp -f $HOME/enjoy24/srpm/$line-[0-9]*.src.rpm $HOME/FedoraUnited/$line/SRPM/
popd  
elif [ ! -f $HOME/FedoraUnited/$line/SRPM/$rpm_source ]; then
	mkdir -p $HOME/FedoraUnited/$line/SRPM/ 
	cp -f $HOME/enjoy24/srpm/$line-[0-9]*.src.rpm $HOME/FedoraUnited/$line/SRPM/
fi
done <"$file"


# repository

pushd $HOME/FedoraUnited/
while IFS= read -r line; do
        # display $line or do something with $line
#########################
# Configuration
# Replace SSH_USERNAME, SSH_PASS with your details
 repo_name=$line
 username=SSH_USERNAME
 token=SSH_PASS
#########################

pushd $HOME/FedoraUnited/$repo_name
if [ -f $HOME/FedoraUnited/$repo_name/.git/description ]; then
git add .
git commit -m "Updated"
git fetch origin
git push origin master
git config --global credential.helper "cache --timeout=3600"
 else

 echo -n "Creating Github repository '$repo_name' ..."
 curl -u "$username:$token" https://api.github.com/orgs/FedoraUnited/repos -d '{"name":"'$line'"}' 
 echo " done."
 echo -n "Pushing local code to remote ..."

if [ ! -f $HOME/FedoraUnited/$repo_name/README.md ]; then
cat *.spec | grep Name: |  awk -F'Name:' '{print $2}' | sed 's/^/#/' > README.md
echo ' ' >> README.md
cat *.spec | grep Summary: |  awk -F'Summary:' '{print $2}' | sed 's/^/Summary:/' | uniq -w 1 >> README.md
echo ' ' >> README.md
cat *.spec | grep Version: |  awk -F'Version:' '{print $2}' | sed 's/^/Version:/' >> README.md
echo ' ' >> README.md
cat *.spec | grep License: |  awk -F'License:' '{print $2}' | sed 's/^/License:/' >> README.md
echo ' ' >> README.md
cat *.spec | grep URL: |  awk -F'URL:' '{print $2}' | sed 's/^/Url:/' >> README.md
 fi
rm -rf .git/
git init
git add .
git commit -m "first commit"
#git remote add origin git@github.com:FedoraUnited/$repo_name.git
git remote add origin https://github.com/FedoraUnited/$repo_name.git
git config --global credential.helper "cache --timeout=3600"
git push --force --set-upstream origin master
git config --global credential.helper "cache --timeout=3600"
echo 'complete!'
fi
popd

done <"$file"
popd


wait ${!}

pushd /tmp/
rm -f /tmp/packages.txt
rm -f *.src.rpm
popd
